### ISSUE TITLE
不知道为什么启动的时候报错，can't resolve node:assert

### ISSUE THREAD

**Issue by zhu2206926093** [docgeni/docgeni#541]
⠹ Start building library(ng-lc-dpp-lib)...can't resolve node:assert
can't resolve node:assert
Error: Debug Failure. False expression.
    at resolveModuleNamesReusingOldState (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:119850:26)
    at processImportedModules (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121296:35)
    at findSourceFileWorker (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121076:17)
    at findSourceFile (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120922:26)
    at E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120871:85
    at getSourceFileFromReferenceWorker (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120837:34)
    at processSourceFile (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120871:13)
    at E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121175:17
    at Object.forEach (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:181:30)
    at processReferencedFiles (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121174:16)
ℹ Error: Debug Failure. False expression.
    at resolveModuleNamesReusingOldState (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:119850:26)
    at processImportedModules (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121296:35)
    at findSourceFileWorker (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121076:17)
    at findSourceFile (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120922:26)
    at E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120871:85
    at getSourceFileFromReferenceWorker (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120837:34)
    at processSourceFile (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:120871:13)
    at E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121175:17
    at Object.forEach (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:181:30)
    at processReferencedFiles (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\ngdoc\node_modules\typescript\lib\typescript.js:121174:16)
TypeError: this.examples is not iterable
    at LibraryComponentImpl.emitExamples (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\library-component.js:415:36)
    at async LibraryComponentImpl.onEmit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\library-component.js:73:9)
    at async LibraryComponentImpl.emit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\emitter.js:10:9)
    at async LibraryBuilderImpl.onEmit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\library-builder.js:94:40)
    at async LibraryBuilderImpl.emit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\emitter.js:10:9)
    at async LibrariesBuilder.onEmit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\libraries-builder.js:73:35)
    at async LibrariesBuilder.emit (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\builders\emitter.js:10:9)
    at async DocgeniCompilationImpl.run (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\compilation.js:57:45)
    at async Docgeni.run (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\core\lib\docgeni.js:78:13)
    at async Object.handler (E:\digi\web\FrontEnd\ng-lc-dpp\node_modules\@docgeni\cli\lib\serve.js:34:9)

**Comment by zhu2206926093** [comment]
之前是可以的，但是有一次合并代码就不行了

**Comment by zhu2206926093** [comment]
已解决，组件库中引入了跟node api相关的东西 去除就好了
